### ISSUE TITLE
GC benchmarks

### ISSUE THREAD

**Issue by HoundThe** [dotnet/performance#1284]
Hi!
I am trying to run your default GC test suite, but I don't how if it's even possible to use existing coreclr of dotnet version on my machine and not one built from dotnet/runtime repository? I see that the repo_path: (in the readme they are named core_root) has to be a git repository aswell otherwise python throws exception while running a test.

**Comment by billwert** [comment]
cc @ivdiazsa

**Comment by ivdiazsa** [comment]
Hi @HoundThe,

Running GC Benchmarking Infra with the default `dotnet` installation on your machine is not a currently supported scenario. The tool was developed with the intent to measure performance while working on dotnet runtime development. That said, it is actually possible to run benchmarks using your `dotnet` installation, but requires additional setup I will explain here.

You have to build `GCPerfSim` as a _self-contained_ app to achieve this. This example will assume you have .NET Core 3.1 on your machine:

1. Go to `/performance/src/benchmarks/gc/src/exec/GCPerfSim`.
2. Build with the following command:
`dotnet publish -f netcoreapp3.1 -r win-x64 -c release --self-contained`
With this command, we are targeting your installation of .NET Core 3.1 on a Windows-x64 machine, under Release configuration (for benchmarks, this is what you want).
3. Get the path of your newly generated `GCPerfSim.exe`. It should be something like:
`/performance/artifacts/bin/GCPerfSim/release/netcoreapp3.1/win-x64/publish/GCPerfSim.exe`
Don't forget the `publish` directory on the path.
4. Make the following edits to your _yaml_ test file (e.g. _normal_server.yaml_):
    * Change `core_root` or `repo_path` to `self_contained: true`.
    * After each benchmark, add the path to the executable:
``` yaml
0gb:
  executable: /performance/artifacts/bin/GCPerfSim/release/netcoreapp3.1/win-x64/publish/GCPerfSim.exe
  arguments:
    <arguments go here>

2gb:
  executable: /performance/artifacts/bin/GCPerfSim/release/netcoreapp3.1/win-x64/publish/GCPerfSim.exe
  arguments:
    <arguments go here>
```
5. Run the test as you normally would.

Hope this helps in your tests!

P.D. If you have a `Core_Root` built from the `runtime` repo, but it is located outside your local repository directory, just tell the _yaml_ file so by using `core_root` instead of `repo_path` (which should be the default behavior when generating the suites).
